name = "a-better-weather-kisruptiv"
main = "src/worker.mjs"
compatibility_date = "2026-07-08"

[assets]
directory = "./static"
binding = "ASSETS"

[vars]
DEFAULT_LEARNING_CITIES = "Berlin,Muenchen,Hamburg,Coburg"

[[d1_databases]]
binding = "DB"
database_name = "a_better_weather"
database_id = "f6354b15-c27a-4b34-8ee6-60e37de4dfbe"

[triggers]
crons = ["12 5 * * *", "22 19 * * *"]
