name = "a-better-weather-kisruptiv"
main = "src/worker.mjs"
compatibility_date = "2026-07-08"

[assets]
directory = "./static"
binding = "ASSETS"

[vars]
DEFAULT_LEARNING_CITIES = "Berlin,Muenchen,Nuernberg,Hamburg,Coburg"

[[d1_databases]]
binding = "DB"
database_name = "a_better_weather"
database_id = "REPLACE_WITH_CLOUDFLARE_D1_DATABASE_ID"

[triggers]
crons = ["12 5 * * *", "22 19 * * *"]
